### PR TITLE
Add support for sessions

### PR DESCRIPTION
**Pull request by Xefir**

### CODE REVIEW

**Review by scottb4rd — APPROVED** [review]

**Comment by leonidcan** [comment]
Can this be merged? Really no use without this.

**Comment by leonidcan** [comment]
I tried to merge this into my local branch, unfortunately it seems not working, only 1st request coming through and second one is returning this error:
 ""Error: Error solving the challenge. HTTPConnectionPool(host='localhost', port=55786): Max retries exceeded with url: /session/ac25f06ba25d84c2ee9de6ba16f891dc/execute/sync (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000023FBB91D750>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))"

**Comment by zongzheng123** [comment]
There is a bug, repeat  session create not be forbided.

**Comment by Xefir** [comment]
Sorry for the late response, but @zongzheng123 , this is fixed, thank you :)

**Comment by iamumairayub** [comment]
can this be dockerized so we can just pull this from docker?

**Comment by Xefir** [comment]
@iamumairayub Here it is : https://hub.docker.com/r/xefir/flaresolverr

Please keep in mind that is a temporary solution and I might delete this image when this PR will be merged.

**Comment by iamumairayub** [comment]
thanks, can you also answer this https://github.com/FlareSolverr/FlareSolverr/discussions/729

**Comment by Xefir** [comment]
Closing this PR. @furdarius has greatly improve my work, big thanks to him. You can see his PR here : https://github.com/FlareSolverr/FlareSolverr/pull/736

**Comment by ngosang** [comment]
https://github.com/FlareSolverr/FlareSolverr/releases/tag/v3.1.0

**Pull request closed without merging**
