### PR TITLE
Cloudflare fix 3

### PR DESCRIPTION
**Pull request by digitalnomad91**
The workaround didn't work until I commented out options in src/utils.py that I didn't need, but I am unsure which one(s) are causing it to fail at this point. Anyone else, feel free to try to narrow it down as I know it's not ideal to just comment them all out. I need to get some sleep, but if it's not done later today then I'll give it a second look. 

~ Peace

### CODE REVIEW

**Comment by tifo71** [comment]
Please update windows version with bypass attack mode.

**Comment by TomGUN02** [comment]
> Please update windows version with bypass attack mode.

Not to sound rude or anything but we all want to get Ygg back and really this isn't the place for these kinds or requests. This is github, made to contribute and not a forum.

**Comment by cedric-bour** [comment]
**Challenge not resolved for  yygtorrent, but with the change, working**

**no work:**
```
driver.get(req.url)
```
**work:**
```
with driver:
    driver.get(req.url)
```

**Comment by digitalnomad91** [comment]
@ngosang Seems to still be working for me, what was the problem that you ran into? That's awesome a permanent fix is out though, thanks a lot! I didn't expect for this PR to get merged into main anyways as I had sloppily commented out a bunch of options and stuff in src/utils.py, but some people in another thread asked me to implement it as a PR instead of the standalone / new repo I had initially created. I'd be curious to know why it didn't work for you if you don't mind sharing, but I suppose it's probably a moot point now that an official update is out :)

**Comment by ngosang** [comment]
It just didn't solved the challenge. The read fix was this fbc71516f5e1bf8c3a89d022b60b01a2c1949ed7

**Pull request closed without merging**
