### PR TITLE
[FIX] Challenge YGGTorrent Instant

### PR DESCRIPTION
**Pull request by cedric-bour**
**Challenge not resolved for  yggtorrent, but with this fix, challenge resolved instant**

**not working:**
```
driver.get(req.url)
```
**working:**
```
with driver:
    driver.get(req.url)
```

### CODE REVIEW

**Comment by RudyBzhBzh** [comment]
Thanks ! It works for me.
(Just had to manually edit these 2 lines inside my docker)

**Comment by JeremyGraffan** [comment]
Thanks, it works for me too.
Installation type : Rebuild docker image from your branch.

**Comment by rawandahmad698** [comment]
I have a fork of flaresolver that bypasses cloudflare and is up to date with proxy & session support

https://github.com/rawandahmad698/pyCFSolver

**Comment by cedric-bour** [comment]
> Is it related to this issue #846 ?

Yes

**Comment by almottier** [comment]
I confirm it fixes my issue #846 , thank you

**Comment by Uruknara** [comment]
> I have a fork of flaresolver that bypasses cloudflare and is up to date with proxy & session support
> 
> https://github.com/rawandahmad698/pyCFSolver

Why making a fork if you can just make a pull request on it so everybody can have the fonctionality and keep a docker image, cause a majority of the people using flaresolverr use it with docker I think ?

**Comment by Uruknara** [comment]
Me too, working like a charm now

**Comment by tifo71** [comment]
Hello it's possible to integrate the fix on flaresolverr windows version ? I'm on windows 11

**Comment by sec0nn** [comment]
Working just fine, thanks bro!

**Comment by Brattac** [comment]
Hi,

Could someone tell me how to proceed to add this fix? Never did on Docker

I'm on a Synology NAS using a docker image with Container Manager.

BR,

**Comment by cedric-bour** [comment]
> Hi,
> 
> Could someone tell me how to proceed to add this fix? Never did on Docker
> 
> I'm on a Synology NAS using a docker image with Container Manager.
> 
> BR,

Hi,

You can build source with my fixe
`docker build -t myflaresolverr .`
And run container with this image

**Comment by Zalatis** [comment]
> > > Hi,
> > > Could someone tell me how to proceed to add this fix? Never did on Docker
> > > I'm on a Synology NAS using a docker image with Container Manager.
> > > BR,
> > 
> > 
> > Hi,
> > You can build source with my fixe `docker build -t myflaresolverr:latest .` And run container with this image
> 
> docker build -t myflaresolverr:latest
> 
> is that the good command to build with the fix ? I tried but pulled the original repo so the fix isn't inside

Go wherever you want the hotfix to be using `cd /opt/docker` or whatever
`git clone https://github.com/cedric-bour/FlareSolverr.git`
`cd FlareSolverr`
`docker build -t flaresolverr-hotfix .`

**Comment by ngosang** [comment]
@ilike2burnthing I'm doing some tests. If everything goes well you can expect a new release of FlareSolverr today.

**Comment by ngosang** [comment]
@ilike2burnthing I will review that links.

@cedric-bour This fix is working but I don't understand how it works. Could you explain it to me?

**Comment by mathieu-dms** [comment]
> confirm fix is working. just edit your docker container with docker exec -u 0 -it container /bin/bash edit the file flaresolverr_service.py at specified lines thanks for the fix and for sharing.

Hi, can you explain how you edit the file ? I'am on Uraid, i can see the file on the container's console but i don't know how to edit it ? Thanks !

**Comment by tifo71** [comment]
Hello Flaresolverr windows version will be updated with fix ?

**Comment by cedric-bour** [comment]
> @ilike2burnthing I will review that links.
> 
> @cedric-bour This fix is working but I don't understand how it works. Could you explain it to me?

I don't really have an answer. I viewed in debug log while waiting for a page with a title, but I don't understand because this page is okay. So, I created a virtual machine and tested with a small Python script to reproduce the 'bug' with Chromium without headless mode.

I view that Chromium exits after 1 or 2 seconds maximum, which indicates that the same bug occurs with flaresolverr. Therefore, I read examples in Google for chromium-webdriver and tested different configurations, and I view that using 'with driver' keeps the page!

So, why does this happen?
I think using 'with' in Python keep a 'lock' or has some other similar effect, but I can't really explain it.

**Comment by ilike2burnthing** [comment]
@tifo71 yes

**Comment by tifo71** [comment]
> @tifo71 yes

Great because i'm in windows 11 and it's easy with windows version. Thanks.

do you think you'll be able to put the new version online soon ?

**Comment by erqz0** [comment]
> 

You can use Vi in the container to edit the file 
(once you have run the docker exec command from your unraid terminal)

**Comment by erqz0** [comment]
> > confirm fix is working. just edit your docker container with docker exec -u 0 -it container /bin/bash edit the file flaresolverr_service.py at specified lines thanks for the fix and for sharing.
> 
> Hi, can you explain how you edit the file ? I'am on Uraid, i can see the file on the container's console but i don't know how to edit it ? Thanks !

You can use Vi in the container to edit the file
(once you have run the docker exec command from your unraid terminal)

**Comment by tifo71** [comment]
> > > confirm fix is working. just edit your docker container with docker exec -u 0 -it container /bin/bash edit the file flaresolverr_service.py at specified lines thanks for the fix and for sharing.
> > 
> > 
> > Hi, can you explain how you edit the file ? I'am on Uraid, i can see the file on the container's console but i don't know how to edit it ? Thanks !
> 
> You can use Vi in the container to edit the file (once you have run the docker exec command from your unraid terminal)

And how edit file with docker or portainer in OMV ?

**Comment by Jeanball** [comment]
Thanks a lot!
Works like a charm.

On my server:

```
git clone https://github.com/cedric-bour/FlareSolverr.git in a folder of your choice (In my case, in /opt)
cd Flaresolverr
docker build -t flaresolverr-hotfix .
```


And in my docker-compose, I removed this:
`    image: ghcr.io/flaresolverr/flaresolverr:latest`

And I added this: 
```
    image: flaresolverr-hotfix
    build: /opt/Flaresolverr (The place I downloaded the source codes of Cedric)
```

**Comment by Luttymix** [comment]
Pulled freshly flaresolverr, modified the 4 lines with docker exec cmd but nothing works so far @home

**Comment by ngosang** [comment]
FlareSolverr 1.3.0 is WIP.
I'm resolving some issues for Linux ARM and Windows but I'm close.

**Comment by ngosang** [comment]
FlareSolverr 3.3.0 released =>  https://github.com/FlareSolverr/FlareSolverr/releases/tag/v3.3.0

@ilike2burnthing could you test the windows binaries? I updated pyInstaller but I not sure if that is enough.

**Comment by Uruknara** [comment]
> FlareSolverr 3.3.0 released => https://github.com/FlareSolverr/FlareSolverr/releases/tag/v3.3.0
> 
> @ilike2burnthing could you test the windows binaries? I updated pyInstaller but I not sure if that is enough.

Little problem right now, im running the v3.3.0 but the docker container keep blocking on this 
https://img.uruk.dev/damp-blueviolet-americanwarmblood
do you have any idea of what it could be ?

**Comment by ngosang** [comment]
@Uruknara Please open another issue and give details about your Host machine.

This fix was included in 22ed3d324bd697eba90a1fcf1790b51e7ac9809a Thank you all!

**Comment by tifo71** [comment]
@cedric-bour Thanks for the fix. it work like a charm

**Comment by ilike2burnthing** [comment]
@ngosang running from source and the pre-compiled binaries both work.

**Comment by ngosang** [comment]
The real fix was fbc71516f5e1bf8c3a89d022b60b01a2c1949ed7
Included in https://github.com/FlareSolverr/FlareSolverr/releases/tag/v3.3.1

**Pull request closed without merging**
