### PR TITLE
Added dev tools open tab patch to fix CF breakage issue.

### PR DESCRIPTION
**Pull request by digitalnomad91**
Temporarily added patch from here: https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/1388

### CODE REVIEW

**Comment by ilike2burnthing** [comment]
Unfortunately this breaks headless mode on Windows.

**Comment by benkrej** [comment]
Are you using `headless-new`?

**Comment by ilike2burnthing** [comment]
As far as I'm aware, yes:

https://github.com/FlareSolverr/FlareSolverr/blob/b8768ae17d26c11ecd26f22202b344fb4fcae69a/src/undetected_chromedriver/__init__.py#L374-L379

Even with https://github.com/FlareSolverr/FlareSolverr/commit/a9d1a2de2d3350aa60cd116423fce49d9e261b86 patch reverted, `--headless=new` results in the same behaviour.

**Comment by benkrej** [comment]
That is interesting, I am only using headless mode and it's working without any issues now.

**Comment by gingerbeardman** [comment]
There's a second workaround (open new tab using js, which will work for captcha solving)

**Comment by ipaqi** [comment]
> 

I didn't get how to implement that with this current hotfix. Can you indicate for me where in the code this bit should go?

**Comment by digitalnomad91** [comment]
@ipaqi in src/utils add this around line 57:

options.add\_argument("--auto-open-devtools-for-tabs") 

I didn't rebuild the docker image or anything so you'll have to build a custom image and run that container yourself, or just run:

python3 src/flaresolverr.py

and it should spin right up. I'd recommend running that in tmux or screen, or setting up a systemd service so that it doesn't stop running when your SSH session disconnects.

**Comment by digitalnomad91** [comment]
@ilike2burnthing That's unfortunate, I'm only running on Debian and would probably use WSL if I were on Windows. Highly recommend using WSL rather than Powershell / Windows CLI. Windows always tends to have weird little issues like that ime. Hopefully an official resolution will come out soon, but for now at least we have this one (and apparently another workaround as well that @gingerbeardman mentioned in the cokmment above). I've had this kind of fight with Google Drive in the past when it came to streaming video from there, and unfortunately I fear that this is going to play out similar to that. It's more or less an arms race / war of attrition, and eventually I got tired of fighting because it becames increasingly difficult to find a good workaround. Honestly I hate relying on 3rd parties for data, particularly in situations like this where this is no official API. Sometimes that's the only real choice you have though. Anyway, good like guys!

**Comment by digitalnomad91** [comment]
I'll try to get another PR (or at least comment a tist or something) with the 2nd workaround implemented, as well as a dockerfile for building a custom image and running a container as I assume that's how most people used flaresolverr. I'll also try to get up and example systemd service file as well. Alternatively for now I recommend just running python3 src/Flaresolverr.py in a tmux session, or simply redirect the output to a log file and in detached mode, then you can just tail the log file. An actual docker container or a systemd service would be a bit more ideal, however. I may make another PR (and update this one) but I'm doubting these will make it into main as they are a bit "hacky" so you'll have to do one of the above methods and/or just pull this branch for now (and perhaps the next PR make which will be for the 2nd workaround and also hopefully including a dockerfile and systemd examples for this PR and the next one). Good luck everyone, hopefully we can get an official fix merged into the main branch soon!

**Comment by ilike2burnthing** [comment]
I'll take hacky over non-functional. Worst-case scenario, it's reverted when a proper fix comes along.

**Comment by gingerbeardman** [comment]
I implemented this manually in exactly the way done in your PR and it's working for me. Cheers!

**Comment by ilike2burnthing** [comment]
https://github.com/FlareSolverr/FlareSolverr/pull/816

**Pull request closed without merging**
