### PR TITLE
undetected_chromedriver 3.5.0

### LINKED ISSUE #801: Can't start Flaresolverr after python-selenium 4.10 update
### Have you checked our README?

- [X] I have checked the README

### Have you followed our Troubleshooting?

- [X] I have followed your Troubleshooting

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Have you checked the discussions?

- [X] I have read the Discussions

### Environment

```markdown
- FlareSolverr version: 3.2.0
- Last working FlareSolverr version: 3.2.0
- Operating system: Arch Linux
- Are you using Docker: [yes/no] no
- FlareSolverr User-Agent (see log traces or / endpoint): got none
- Are you using a VPN: [yes/no] no
- Are you using a Proxy: [yes/no] yes
- Are you using Captcha Solver: [yes/no] no
- If using captcha solver, which one:
- URL to test this issue: -
```

### Description

Got logs down there. I can't figure which dependency or something doing this error.

### Logged Error Messages

```text
00:08:52 systemd[1]: Started FlareSolverr.
00:08:53 flaresolverr[26508]: 2023-06-16 00:08:53 INFO     FlareSolverr 3.2.0
00:08:53 flaresolverr[26508]: 2023-06-16 00:08:53 INFO     Testing web browser installation...
00:08:53 flaresolverr[26508]: 2023-06-16 00:08:53 INFO     Platform: Linux-6.3.8-arch1-1-x86_64-with-glibc2.37
00:08:53 flaresolverr[26508]: 2023-06-16 00:08:53 INFO     Chrome / Chromium path: /usr/bin/chromium
00:08:53 flaresolverr[26508]: 2023-06-16 00:08:53 INFO     Chrome / Chromium major version: 114
00:08:53 flaresolverr[26508]: 2023-06-16 00:08:53 INFO     Launching web browser...
00:08:56 flaresolverr[26508]: Traceback (most recent call last):
00:08:56 flaresolverr[26508]:   File "/opt/flaresolverr/utils.py", line 202, in get_user_agent
00:08:56 flaresolverr[26508]:     driver = get_webdriver()
00:08:56 flaresolverr[26508]:              ^^^^^^^^^^^^^^^
00:08:56 flaresolverr[26508]:   File "/opt/flaresolverr/utils.py", line 88, in get_webdriver
00:08:56 flaresolverr[26508]:     driver = uc.Chrome(options=options, browser_executable_path=browser_executable_path,
00:08:56 flaresolverr[26508]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
00:08:56 flaresolverr[26508]:   File "/opt/flaresolverr/undetected_chromedriver/__init__.py", line 447, in __init__
00:08:56 flaresolverr[26508]:     super(Chrome, self).__init__(
00:08:56 flaresolverr[26508]: TypeError: WebDriver.__init__() got an unexpected keyword argument 'executable_path'
00:08:56 flaresolverr[26508]: During handling of the above exception, another exception occurred:
00:08:56 flaresolverr[26508]: Traceback (most recent call last):
00:08:56 flaresolverr[26508]:   File "/opt/flaresolverr/flaresolverr.py", line 102, in <module>
00:08:56 flaresolverr[26508]:     flaresolverr_service.test_browser_installation()
00:08:56 flaresolverr[26508]:   File "/opt/flaresolverr/flaresolverr_service.py", line 72, in test_browser_installation
00:08:56 flaresolverr[26508]:     user_agent = utils.get_user_agent()
00:08:56 flaresolverr[26508]:                  ^^^^^^^^^^^^^^^^^^^^^^
00:08:56 flaresolverr[26508]:   File "/opt/flaresolverr/utils.py", line 206, in get_user_agent
00:08:56 flaresolverr[26508]:     raise Exception("Error getting browser User-Agent. " + str(e))
00:08:56 flaresolverr[26508]: Exception: Error getting browser User-Agent. WebDriver.__init__() got an unexpected keyword argument 'executable_path'
00:08:56 systemd[1]: flaresolverr.service: Main process exited, code=exited, status=1/FAILURE
00:08:56 systemd[1]: flaresolverr.service: Failed with result 'exit-code'.
00:08:57 systemd[1]: Stopped FlareSolverr.
```

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by DX37**
After Selenium got updated to 4.10, FlareSolverr stopped to work.
This fixes #801 - updates undetected_chromedriver to 3.5.0.

### CODE REVIEW

**Comment by DX37** [comment]
@ngosang Will you review this PR, please?

**Comment by ilike2burnthing** [comment]
Please apply the following patches:
https://github.com/FlareSolverr/FlareSolverr/commit/410ee7981fab7fc3613dbe69cf90d3996b86e060
https://github.com/FlareSolverr/FlareSolverr/commit/9b2c602a1f3f5e7cd26fcc30abe7d5cbfd73eab1

There's also https://github.com/FlareSolverr/FlareSolverr/commit/a9d1a2de2d3350aa60cd116423fce49d9e261b86, but I'm not sure how this would work with the changes to undetected_chromedriver v3.5.0

**Comment by muhualing** [comment]
Any updates on this? @DX37 @ilike2burnthing

**Comment by DX37** [comment]
> Any updates on this? @DX37 @ilike2burnthing

Can't really tell. With or without applied patches, i'm getting this errors:
```
2023-07-17 19:50:39 INFO     FlareSolverr 3.2.2                                                          
2023-07-17 19:50:39 INFO     Testing web browser installation...
2023-07-17 19:50:39 INFO     Platform: Linux-6.4.3-arch1-1-x86_64-with-glibc2.37                   
2023-07-17 19:50:39 INFO     Chrome / Chromium path: /usr/bin/chromium
2023-07-17 19:50:39 INFO     Chrome / Chromium major version: 115
2023-07-17 19:50:39 INFO     Launching web browser...                     
Traceback (most recent call last):
  File "/home/dx37/FlareSolverr/src/utils.py", line 218, in get_user_agent
    driver = get_webdriver()
             ^^^^^^^^^^^^^^^
  File "/home/dx37/FlareSolverr/src/utils.py", line 97, in get_webdriver
    driver = uc.Chrome(options=options, browser_executable_path=browser_executable_path,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dx37/FlareSolverr/src/undetected_chromedriver/__init__.py", line 258, in __init__
    self.patcher.auto()
  File "/home/dx37/FlareSolverr/src/undetected_chromedriver/patcher.py", line 158, in auto
    release = self.fetch_release_number()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dx37/FlareSolverr/src/undetected_chromedriver/patcher.py", line 222, in fetch_release_number
    return LooseVersion(urlopen(self.url_repo + path).read().decode())
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 525, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 634, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 563, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dx37/FlareSolverr/src/flaresolverr.py", line 102, in <module>
    flaresolverr_service.test_browser_installation()
  File "/home/dx37/FlareSolverr/src/flaresolverr_service.py", line 72, in test_browser_installation
    user_agent = utils.get_user_agent()
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dx37/FlareSolverr/src/utils.py", line 222, in get_user_agent
    raise Exception("Error getting browser User-Agent. " + str(e))
Exception: Error getting browser User-Agent. HTTP Error 404: Not Found
```

**Comment by ilike2burnthing** [comment]
Thanks for the tabs/spaces fix.

Working ok on Windows. Can you try with Chrome instead of Chromium?

**Comment by DX37** [comment]
> Thanks for the tabs/spaces fix.
> 
> Working ok on Windows. Can you try with Chrome instead of Chromium?
> 
> Also, can you try running the current `master` branch from source with Chromium, see if it gives the same error?

I got weird test results.

Flaresolverr with `Google Chrome 114 Stable` with this PR `undetected_chromedriver_upd` patch works:
```
2023-07-17 21:22:45 INFO     FlareSolverr 3.2.2
2023-07-17 21:22:45 INFO     Testing web browser installation...
2023-07-17 21:22:45 INFO     Platform: Linux-6.4.3-arch1-1-x86_64-with-glibc2.37
2023-07-17 21:22:45 INFO     Chrome / Chromium path: /usr/bin/google-chrome-stable
2023-07-17 21:22:45 INFO     Chrome / Chromium major version: 114
2023-07-17 21:22:45 INFO     Launching web browser...
2023-07-17 21:22:47 INFO     FlareSolverr User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
2023-07-17 21:22:47 INFO     Test successful!
2023-07-17 21:22:47 INFO     Serving on http://0.0.0.0:8191
```
but without this PR I got this error:
```
2023-07-17 21:20:03 INFO     FlareSolverr 3.2.2
2023-07-17 21:20:03 INFO     Testing web browser installation...
2023-07-17 21:20:03 INFO     Platform: Linux-6.4.3-arch1-1-x86_64-with-glibc2.37
2023-07-17 21:20:03 INFO     Chrome / Chromium path: /usr/bin/google-chrome-stable
2023-07-17 21:20:03 INFO     Chrome / Chromium major version: 114
2023-07-17 21:20:03 INFO     Launching web browser...
Traceback (most recent call last):
  File "/home/dx37/FlareSolverr/src/utils.py", line 218, in get_user_agent
    driver = get_webdriver()
             ^^^^^^^^^^^^^^^
  File "/home/dx37/FlareSolverr/src/utils.py", line 97, in get_webdriver
    driver = uc.Chrome(options=options, browser_executable_path=browser_executable_path,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dx37/FlareSolverr/src/undetected_chromedriver/__init__.py", line 447, in __init__
    super(Chrome, self).__init__(
TypeError: WebDriver.__init__() got an unexpected keyword argument 'executable_path'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dx37/FlareSolverr/src/flaresolverr.py", line 102, in <module>
    flaresolverr_service.test_browser_installation()
  File "/home/dx37/FlareSolverr/src/flaresolverr_service.py", line 72, in test_browser_installation
    user_agent = utils.get_user_agent()
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dx37/FlareSolverr/src/utils.py", line 222, in get_user_agent
    raise Exception("Error getting browser User-Agent. " + str(e))
Exception: Error getting browser User-Agent. WebDriver.__init__() got an unexpected keyword argument 'executable_path'
```

Flaresolverr with Chromium 115 with or without this PR `undetected_chromedriver_upd` patch (different lines, same issue):
```
2023-07-17 21:21:20 INFO     FlareSolverr 3.2.2                                                          
2023-07-17 21:21:20 INFO     Testing web browser installation...
2023-07-17 21:21:20 INFO     Platform: Linux-6.4.3-arch1-1-x86_64-with-glibc2.37                   
2023-07-17 21:21:20 INFO     Chrome / Chromium path: /usr/bin/chromium
2023-07-17 21:21:20 INFO     Chrome / Chromium major version: 115
2023-07-17 21:21:20 INFO     Launching web browser...                     
Traceback (most recent call last):
  File "/home/dx37/FlareSolverr/src/utils.py", line 218, in get_user_agent
    driver = get_webdriver()
             ^^^^^^^^^^^^^^^
  File "/home/dx37/FlareSolverr/src/utils.py", line 97, in get_webdriver
    driver = uc.Chrome(options=options, browser_executable_path=browser_executable_path,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dx37/FlareSolverr/src/undetected_chromedriver/__init__.py", line 247, in __init__
    self.patcher.auto()
  File "/home/dx37/FlareSolverr/src/undetected_chromedriver/patcher.py", line 124, in auto
    release = self.fetch_release_number()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dx37/FlareSolverr/src/undetected_chromedriver/patcher.py", line 145, in fetch_release_number
    return LooseVersion(urlopen(self.url_repo + path).read().decode())
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 525, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 634, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 563, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dx37/FlareSolverr/src/flaresolverr.py", line 102, in <module>
    flaresolverr_service.test_browser_installation()
  File "/home/dx37/FlareSolverr/src/flaresolverr_service.py", line 72, in test_browser_installation
    user_agent = utils.get_user_agent()
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dx37/FlareSolverr/src/utils.py", line 222, in get_user_agent
    raise Exception("Error getting browser User-Agent. " + str(e))
Exception: Error getting browser User-Agent. HTTP Error 404: Not Found
```

**Comment by ilike2burnthing** [comment]
u_c issue? https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/1259#issuecomment-1546736798

I think this can be merged, although I won't publish a new build with it yet. Any objections?

**Comment by DX37** [comment]
> u_c issue? [ultrafunkamsterdam/undetected-chromedriver#1259 (comment)](https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/1259#issuecomment-1546736798)
> 
> I think this can be merged, although I won't publish a new build with it yet. Any objections?

I'm building Ungoogled Chrome 114 to test 114 version with this PR.
Despite this, I have no objections.

**Comment by garfield69** [comment]
i'm running win10 and flaresolverr from source, with chrome 114
after fetching the latest flaresolverr source and restarting flaresolverr I get this:
```
C:\Users\Garfield69\Documents\GitHub\FlareSolverr>python src/flaresolverr.py
2023-07-18 06:51:28 INFO     FlareSolverr 3.2.2
2023-07-18 06:51:28 INFO     Testing web browser installation...
2023-07-18 06:51:28 INFO     Platform: Windows-10-10.0.19045-SP0
2023-07-18 06:51:28 INFO     Chrome / Chromium path: C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
2023-07-18 06:51:28 INFO     Chrome / Chromium major version: 114
2023-07-18 06:51:28 INFO     Launching web browser...
Traceback (most recent call last):
  File "C:\Users\Garfield69\Documents\GitHub\FlareSolverr\src\utils.py", line 218, in get_user_agent
    driver = get_webdriver()
  File "C:\Users\Garfield69\Documents\GitHub\FlareSolverr\src\utils.py", line 104, in get_webdriver
    shutil.copy(driver.patcher.executable_path, PATCHED_DRIVER_PATH)
  File "C:\Users\Garfield69\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 417, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Users\Garfield69\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 234, in copyfile
    raise SameFileError("{!r} and {!r} are the same file".format(src, dst))
shutil.SameFileError: 'C:\\Users\\Garfield69\\appdata\\roaming\\undetected_chromedriver\\chromedriver.exe' and 'C:\\Users\\Garfield69\\appdata\\roaming\\undetected_chromedriver\\chromedriver.exe' are the same file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Garfield69\Documents\GitHub\FlareSolverr\src\flaresolverr.py", line 102, in <module>
    flaresolverr_service.test_browser_installation()
  File "C:\Users\Garfield69\Documents\GitHub\FlareSolverr\src\flaresolverr_service.py", line 72, in test_browser_installation
    user_agent = utils.get_user_agent()
  File "C:\Users\Garfield69\Documents\GitHub\FlareSolverr\src\utils.py", line 222, in get_user_agent
    raise Exception("Error getting browser User-Agent. " + str(e))
Exception: Error getting browser User-Agent. 'C:\\Users\\Garfield69\\appdata\\roaming\\undetected_chromedriver\\chromedriver.exe' and 'C:\\Users\\Garfield69\\appdata\\roaming\\undetected_chromedriver\\chromedriver.exe' are the same file

C:\Users\Garfield69\Documents\GitHub\FlareSolverr>
```
any clues as to what is going on?

**Comment by ilike2burnthing** [comment]
That happened to me randomly one time before, no idea why. Delete the `undetected_chromedriver` folder under `%appdata%` and run again.

**Comment by garfield69** [comment]
OK now. Thanks.

**Comment by DX37** [comment]
> > u_c issue? [ultrafunkamsterdam/undetected-chromedriver#1259 (comment)](https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/1259#issuecomment-1546736798)
> > I think this can be merged, although I won't publish a new build with it yet. Any objections?
> 
> I'm building Ungoogled Chrome 114 to test 114 version with this PR. Despite this, I have no objections.

Built it, works with this version. Can it be because of a 115 version?

**Pull request merged**
