### PR TITLE
Bump version 3.3.9

### PR DESCRIPTION
**Pull request by ilike2burnthing**

### CODE REVIEW

**Comment by GravuTrad** [comment]
Hi. is this normal?:
2023-11-13 21:06:15 INFO     Launching web browser...
version_main cannot be converted to an integer

**Comment by ilike2burnthing** [comment]
Yes. There may be a way to resolve it, but for now I'm just leaving the error in.

**Comment by dxgs2154** [comment]
Do you have any solution for now? I still got error for operating: Centos

**Comment by ilike2burnthing** [comment]
Not an error representative of any actual issue, but changed - https://github.com/FlareSolverr/FlareSolverr/commit/2ecf88895b851eacec75afaa82f08532fe2dc8a6

**Comment by dxgs2154** [comment]
oh okay,

**Comment by ilike2burnthing** [comment]
[v3.3.20](https://github.com/FlareSolverr/FlareSolverr/releases/v3.3.20)

**Pull request merged**
