### PR TITLE
Add FreeBSD support

### LINKED ISSUE #95: Error - Unsupported platform: freebsd
### Instruction on how to enable debug and html trace

(Applicable to Docker only?)

### Environment

**FlareSolverr Version:** v1.2.3

**Docker:** No

**OS:** FreeBSD 11.4 (Jail under TrueNAS Core 12.0-U2.1 (FreeBSD 12.2))

**Last Working FlareSolverr Version:** N/A

**Are you using a proxy or VPN?:** Yes - VPN (at router level)

**Using Captcha Solver:** No

**If using captcha solver, which one:** N/A

**Mono Version:** 6.8.0.105
**Jackett Version:** v0.17.617
**Node Version:** v15.5.1
**npm Version:** 6.14.8

### Description

Installed node & npm through native pkg commands. 
`npm install` fails. Missing fsevents. Might be other major issues here? Forced installation with `-f`.
`npm run build`, then, `npm start`.
Successfully connects from jackett, however, all related indexer tests fail due to Unsupported platform Error.

### Logged Error Messages

root@:/usr/local/share/flaresolverr # npm start

> flaresolverr@1.2.3 start /usr/local/share/flaresolverr
> node ./dist/index.js

2021-03-05T03:00:19.003Z INFO REQ-0 FlareSolverr v1.2.3 listening on http://0.0.0.0:8191
2021-03-05T03:00:28.295Z INFO REQ-1 Incoming request: POST /v1
2021-03-05T03:00:28.296Z INFO REQ-1 Params: {"maxTimeout":60000,"cmd":"request.get","url":"https://www.7torrents.cc/search?query=+&sort=created","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"}
Error: Unsupported platform: freebsd
    at Object.assert (/usr/local/share/flaresolverr/node_modules/puppeteer/lib/helper.js:29:15)
    at BrowserFetcher.setPlatform (/usr/local/share/flaresolverr/node_modules/puppeteer/lib/BrowserFetcher.js:119:22)
    at new BrowserFetcher (/usr/local/share/flaresolverr/node_modules/puppeteer/lib/BrowserFetcher.js:103:14)
    at resolveExecutablePath (/usr/local/share/flaresolverr/node_modules/puppeteer/lib/Launcher.js:488:28)
[...]

2021-03-05T03:20:02.126Z INFO REQ-47 Incoming request: POST /v1
2021-03-05T03:20:02.127Z INFO REQ-47 Params: {"maxTimeout":60000,"cmd":"request.get","url":"https://apibay.org/precompiled/data_top100_recent.json","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"}
Error: Unsupported platform: freebsd
    at Object.assert (/usr/local/share/flaresolverr/node_modules/puppeteer/lib/helper.js:29:15)
    at BrowserFetcher.setPlatform (/usr/local/share/flaresolverr/node_modules/puppeteer/lib/BrowserFetcher.js:119:22)
    at new BrowserFetcher (/usr/local/share/flaresolverr/node_modules/puppeteer/lib/BrowserFetcher.js:103:14)
    at resolveExecutablePath (/usr/local/share/flaresolverr/node_modules/puppeteer/lib/Launcher.js:488:28)
    at ChromeLauncher.launch (/usr/local/share/flaresolverr/node_modules/puppeteer/lib/Launcher.js:57:53)
    at async PuppeteerExtra.launch (/usr/local/share/flaresolverr/node_modules/puppeteer-extra/dist/index.cjs.js:129:25)
    at async Object.create (/usr/local/share/flaresolverr/dist/session.js:49:27)
    at async browserRequest (/usr/local/share/flaresolverr/dist/routes.js:138:11)
    at async request.get (/usr/local/share/flaresolverr/dist/routes.js:189:9)
    at async Object.Router [as default] (/usr/local/share/flaresolverr/dist/routes.js:202:16)
2021-03-05T03:20:02.127Z ERROR REQ-47 Unsupported platform: freebsd

### PR DESCRIPTION
**Pull request by Asthowen**
Added support for FreeBSD, since Google doesn't directly provide a binary for FreeBSD, the user needs to have installed the `chromium` package. 
A copy of the chromedriver executable is made in `~/.undetected_chromedriver`, and a `version.txt` file is also created to repatch the executable if an update has been performed.

- Resolves #95
- Closes #919

### CODE REVIEW

**Comment by ilike2burnthing** [comment]
@FroggMaster / @TheSilasm8 / @Boofie0404 can you all test this?

**Comment by Asthowen** [comment]
For those who want to try this PR, here's what to do:

Install packages:
```sh
pkg install chromium python310 py39-pip xorg-vfbserver
```

Install Python modules:
```sh
python3.9 -m pip install test-requirements.txt && python3.9 -m pip install requirements.txt
```

Run FlareSolverr:
```
python3.9 src/flaresolverr.py 
```

**Comment by SquitchYT** [comment]
I've tested this on FreeBSD 14, and it works perfectly:
```
python3.9 src/flaresolverr.py 
2024-02-26 20:04:34 INFO     FlareSolverr 3.3.13
2024-02-26 20:04:34 INFO     Testing web browser installation...
2024-02-26 20:04:34 INFO     Platform: FreeBSD-14.0-RELEASE-amd64-64bit-ELF
2024-02-26 20:04:34 INFO     Chrome / Chromium path: /usr/local/bin/chrome
2024-02-26 20:04:34 INFO     Chrome / Chromium major version: 121
2024-02-26 20:04:35 INFO     Launching web browser...
2024-02-26 20:04:37 INFO     FlareSolverr User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36
2024-02-26 20:04:37 INFO     Test successful!
2024-02-26 20:04:37 INFO     Serving on http://0.0.0.0:8191
2024-02-26 20:08:03 INFO     Incoming request => POST /v1 body: {'cmd': 'request.get', 'url': 'http://www.google.com/', 'maxTimeout': 60000}
2024-02-26 20:08:05 INFO     Challenge not detected!
2024-02-26 20:08:06 INFO     Response in 2.054 s
2024-02-26 20:08:06 INFO     127.0.0.1 POST http://localhost:8191/v1 200 OK
```

**Comment by ilike2burnthing** [comment]
Thanks!

@Asthowen and @SquitchYT can you both check that FlareSolverr is able to resolve challenges with this code (you will need to update to the current master first):
- https://idope.se/
- https://torrentcore.xyz/

**Comment by ilike2burnthing** [comment]
Oh, @Asthowen can you also amend https://github.com/FlareSolverr/FlareSolverr#from-source-code or add a `From source code (FreeBSD/TrueNAS CORE)` section beneath it?

**Comment by Asthowen** [comment]
> Oh, @Asthowen can you also amend https://github.com/FlareSolverr/FlareSolverr#from-source-code or add a `From source code (FreeBSD/TrueNAS CORE)` section beneath it?

It's done!

**Comment by ilike2burnthing** [comment]
Tested Windows and Docker as well, just to make sure they weren't affected; all good.

Thanks. No point in publishing a new release for this, but it will be included in the next one.

**Comment by ilike2burnthing** [comment]
[v3.3.16](https://github.com/FlareSolverr/FlareSolverr/releases/v3.3.16)

**Comment by FroggMaster** [comment]
I'm a bit late to the party, but I confirmed I was able to run things smoothly with FreeBSD 13.2.
I was reviewing the steps in the ReadMe and saw: https://github.com/FlareSolverr/FlareSolverr?tab=readme-ov-file#systemd-service

Although I had a tough time locating the example file that's mentioned here. I ended up making a shell script to start Flaresolverr, then an rc.d script which can also call the shell script.

Here's the shell script that I created to start Flaresolverr. I saved this in the root of the cloned FlareSolverr directory as: start_flaresolverr.sh
```
#!/bin/sh
DIR="$( cd "$( dirname "$0" )" >/dev/null 2>&1 && pwd )"
/usr/local/bin/python3.9 "$DIR/src/flaresolverr.py" > "$DIR/flaresolverr.log" 2>&1 &
```

Here's the rc.d script for **/usr/local/etc/rc.d** that I modified from the original legacy instructions. There are some residual variables here from the legacy instructions, so this could probably still be cleaned up a bit. 

```
#!/bin/sh
#
# PROVIDE: flaresolverr
# REQUIRE: networking
# KEYWORD: shutdown

# flaresolverr_enable="YES"

. /etc/rc.subr

name="flaresolverr"
rcvar="flaresolverr_enable"

flaresolverr_log_file="/var/log/flaresolverr/flaresolverr.log"

start_precmd=flaresolverr_prestart
stop_postcmd=flaresolverr_poststop

load_rc_config ${name}
# Defaults
# Usable parameter in rc.conf with those default parameter
: ${flaresolverr_enable:=NO}
: ${flaresolverr_daemon_user:=flaresolverr}
: ${flaresolverr_path:="/home/frog/FlareSolverr"}
: ${flaresolverr_LOG_LEVEL:="info"}
: ${flaresolverr_LOG_HTML:="false"}
: ${flaresolverr_CAPTCHA_SOLVER:="false"}
: ${flaresolverr_TZ:="UTC"}
: ${flaresolverr_HEADLESS:="true"}
: ${flaresolverr_BROWSER_TIMEOUT:="40000"}
: ${flaresolverr_PORT:="8191"}
: ${flaresolverr_HOST:="0.0.0.0"}
: ${flaresolverr_TEST_URL:="https://www.google.com"}

procname="flaresolverr.py"  # Specific process name
startscript="<PathToStartScript>/start_flaresolverr.sh"  # Updated to point to your start script

flaresolverr_prestart() {
    echo "Starting Flaresolverr..."
    
    if pgrep -f "$procname" > /dev/null; then
        echo "Flaresolverr is already running."
        exit 0
    fi

    #install -d -o root -g $flaresolverr_daemon_user /var/run/flaresolverr
    install -d -o root -g $flaresolverr_daemon_user /var/log/flaresolverr

    export LOG_LEVEL=$flaresolverr_LOG_LEVEL
    export LOG_HTML=$flaresolverr_LOG_HTML
    export CAPTCHA_SOLVER=$flaresolverr_CAPTCHA_SOLVER
    export TZ=$flaresolverr_TZ
    export HEADLESS=$flaresolverr_HEADLESS
    export BROWSER_TIMEOUT=$flaresolverr_BROWSER_TIMEOUT
    export PORT=$flaresolverr_PORT
    export HOST=$flaresolverr_HOST
    export TEST_URL=$flaresolverr_TEST_URL

    # Set the PATH variable to include the directory containing Chromium executable
    PATH="/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin"
    PATH="$PATH:/usr/local/bin"
    export PATH
	
	$startscript
}

flaresolverr_poststop() {
    if pgrep -f "$procname" > /dev/null; then
        echo "Stopping Flaresolverr."
        pkill -f "$procname"
        sleep 2
        if pgrep -f "$procname" > /dev/null; then
            echo "Failed to stop Flaresolverr."
        else
            echo "Flaresolverr stopped successfully."
        fi
    else
        echo "Flaresolverr is not running."
    fi
}

flaresolverr_status() {
    if pgrep -f "$procname" > /dev/null; then
        echo "Flaresolverr is running."
    else
        echo "Flaresolverr is not running."
    fi
}

case "$1" in
    start)
        flaresolverr_prestart
        ;;
    stop)
        flaresolverr_poststop
        ;;
    restart)
        flaresolverr_poststop
        sleep 2
        flaresolverr_prestart
        ;;
    status)
        flaresolverr_status
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|status}"
        exit 1
        ;;
esac
# I suck at using this, so it's all manual 
# run_rc_command "$1"
exit 0
```

**Comment by ilike2burnthing** [comment]
Not sure if it was intentional and the readme section was missed, but it was removed in change to v3 - https://github.com/FlareSolverr/FlareSolverr/blob/v2.2.10/flaresolverr.service

**Pull request merged**
