### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by francisco-lafe**
Added extra detail for total begginners on how to change the environment variables for windows. It's meant to be a clarification of the process.

The change is minimal and I believe it greatly enhances readibility.

### CODE REVIEW

**Comment by ilike2burnthing** [comment]
Thanks

**Comment by francisco-lafe** [comment]
If you never changed an environment variable from the cmd console the instructions have changed in no meaninful way. 
No one who's looking into using FlareSolverr is looking for increasing the debug level, specially when it comes to using the windows binary. 
Instead, I would use the "HOST" example, as I had it on my original pull request and commit. 
It's your project, you do you, but from a documentation standpoint your commit [6bc5ef7](https://github.com/FlareSolverr/FlareSolverr/pull/1127/commits/6bc5ef7c7d6ea439ff956a032fc389e95a60f7b6) basically looks the same and achieves the same thing I was trying to solve.

**Comment by ilike2burnthing** [comment]
There's a table of environment variables followed by instructions for each platform of how to use said variables. One example is fine.

**Comment by francisco-lafe** [comment]
Understandable, just my opinion, you have yours, and eventually I figured it out, was giving my perspective on the topic.
Bests,

**Pull request merged**
