### PR TITLE
Fix Cloudflare challenge detection

### PR DESCRIPTION
**Pull request by tenettow**
Cloudflare recently changed the HTML page returned for challenges, which means we need to adjust what selector we look for.

### CODE REVIEW

**Comment by ilike2burnthing** [comment]
A very quick test in Docker with ygg.re doesn't resolve the challenge. Will take a closer look later.

**Comment by 21hsmw** [comment]
Cloudflare has also changed things around the challenge checkbox. So we need to update the XPath for that:

```diff
-        checkbox = driver.find_element(
-            by=By.XPATH,
-            value='//*[@id="challenge-stage"]/div/label/input',
-        )
+        checkbox = driver.find_element(
+            by=By.XPATH,
+            value='//*[@id="content"]/div/div/label/input',
+        )
```

**Comment by tenettow** [comment]
Thanks, I re-added the previous selectors (I don't see them anymore but maybe that's just me). I wasn't getting the checkbox, but @21hsmw is right that when it shows up the XPath doesn't work anymore - fixed that too.

**Comment by TheRealBix** [comment]
Do you think you can publish this fix on docker so we can test on various platforms ?

**Comment by ilike2burnthing** [comment]
I'm not home at the moment to test. Either wait a few hours or edit the file using vim and restart the container.

**Comment by Mozeur** [comment]
I test it, it fine for me on ygg.re

```
        checkbox = driver.find_element(
            by=By.XPATH,
-           value='//*[@id="challenge-stage"]/div/label/input',
+           value='//*[@id="content"]/div/div/label/input',
        )
```

Thx

**Comment by Dupinoux** [comment]
Hi,
I have just applied your update.
Seems working fine (image docker built from local on Raspbian).
Thank you for the PR :)

**Comment by ilike2burnthing** [comment]
I'm assuming the idea at the time was to be as specific as possible (they could throw in a dummy hidden checkbox).

**Comment by nanarCss** [comment]
Hi,
I tried also, and it's working, using latest docker version
Thank you for the hot fix :)

**Comment by tifo71** [comment]
how to get the hotfix. Is there a repo where the fix is available please ?

**Comment by ilike2burnthing** [comment]
https://github.com/FlareSolverr/FlareSolverr/pull/1224#issuecomment-2182625878

**Comment by tifo71** [comment]
could someone give me the command with the file path to edit the files it please? That would be really nice.  thanks

**Comment by ObstinateM** [comment]
Hi all, 
I tried with docker and ygg.re, works perfectly. Thanks!

**Comment by tifo71** [comment]
> Hi all, I tried with docker and ygg.re, works perfectly. Thanks!

Great I want to edit the file but how do I do it I also use docker. Is there a way to get the command to go to the folder and edit the file please?

**Comment by ObstinateM** [comment]
> > Hi all, I tried with docker and ygg.re, works perfectly. Thanks!
> 
> Great I want to edit the file but how do I do it I also use docker. Is there a way to get the command to go to the folder and edit the file please?

Yeah, for those wondering :

`docker exec -it <your container name> bash`

then `vim flaresolverr_service.py` (you might use nano or else if you don't know vim) and edit with the changes

And restart your container `docker restart <your container name>`

**Comment by tifo71** [comment]
> > > Hi all, I tried with docker and ygg.re, works perfectly. Thanks!
> > 
> > 
> > Great I want to edit the file but how do I do it I also use docker. Is there a way to get the command to go to the folder and edit the file please?
> 
> Yeah, for those wondering :
> 
> `docker exec -it <your container name> bash`
> 
> then `vim flaresolverr_service.py` (you might use nano or else if you don't know vim) and edit with the changes
> 
> And restart your container `docker restart <your container name>`
great thanks i try

**Comment by bozoweed** [comment]
how can i edit that on my docker container ? :)

**Comment by tifo71** [comment]
@ObstinateM OMG it's possible to put flaresolverr with this fix on a repo for docker ?

**Comment by tenettow** [comment]
Seems like this works for people, should we merge and tag, @ilike2burnthing?

**Comment by bozoweed** [comment]
i think you need to create a nigthly branch , i'm gona used it everytime to keep it more stable than main, because when challenge are broken , we have to wait a long long time to see the fix in production.

do it like you want , but if u do nigthly i'm gona use it for sure

**Comment by bozoweed** [comment]
I have also apply the update manualy and worked like sharmed thanks you so much contributor <3 keep doing <3

**Comment by tifo71** [comment]
> i think you need to create a nigthly branch , i'm gona used it everytime to keep it more stable than main, because when challenge are broken , we have to wait a long long time to see the fix in production.
> 
> do it like you want , but if u do nigthly i'm gona use it for sure
if I understand correctly @ilike2burnthing will updating flaresolverr with the fix as soon as he gets home. Unless some generous soul puts a flaresolverr with the fix on a repo for docker

**Comment by tifo71** [comment]
> I have also apply the update manualy and worked like sharmed thank you so much contributor <3 keep doing <3

Unfortunately I can't edit the file.

**Comment by bozoweed** [comment]
> > I have also apply the update manualy and worked like sharmed thank you so much contributor <3 keep doing <3
> 
> Unfortunately I can't edit the file.



use portaine to have friendly GUI to manage container, then connect to console as root, 

vim flaresolverr_service.py

when you are at line that need to update presse "i" and edit line 

when you done presse "ESC" and then write :wq  (you must write double point w and q ) and presse enter 

restart container , you done Enjoy <3

**Comment by tifo71** [comment]
> > > I have also apply the update manualy and worked like sharmed thank you so much contributor <3 keep doing <3
> > 
> > 
> > Unfortunately I can't edit the file.
> 
> use portainer to have friendly GUI to manage container, then connect to console as root,
> 
> vim flaresolverr_service.py
> 
> when you are at line that need to update presse "i" and edit line
> 
> when you done presse "ESC" and then write :wq (you must write double point w and q ) and presse enter
> 
> restart container , you done Enjoy <3

ok great thanks i understand

**Comment by bozoweed** [comment]
> > Cloudflare has also changed things around the challenge checkbox. So we need to update the XPath for that:
> > ```diff
> >         checkbox = driver.find_element(
> >             by=By.XPATH,
> > -           value='//*[@id="challenge-stage"]/div/label/input',
> > +           value='//*[@id="content"]/div/div/label/input',
> >         )
> > ```
> 
> Hello, I'm trying to change the line in the file but it is read-only. I tried to change the rights with chmod but I need admin perms and I don't have the user password. How can I make the change in the file ? (Sorry for the bother but I'm not familiar with Docker...)

whoami, you must connect as root to edit file also follow my tuto juste 2 comments ago

**Comment by bozoweed** [comment]
> > > I have also apply the update manualy and worked like sharmed thank you so much contributor <3 keep doing <3
> > 
> > 
> > Unfortunately I can't edit the file.
> 
> use portainer to have friendly GUI to manage container, then connect to console as root,
> 
> vim flaresolverr_service.py
> 
> when you are at line that need to update presse "i" and edit line
> 
> when you done presse "ESC" and then write :wq (you must write double point w and q ) and presse enter
> 
> restart container , you done Enjoy <3

this one

**Comment by TristanThomas03** [comment]
Yes my bad, I saw your tuto just after posting :')
I just made the change, but now when I restart the flaresolverr container, it restarts again and again as soon as it's booted...

**Comment by bozoweed** [comment]
> Yes my bad, I saw your tuto just after posting :') I just made the change, but now when I restart the flaresolverr container, it restarts again and again as soon as it's booted...

you can try to recreate it to restore code, then try again , i think you missed some step, ensure triple time that line was correct

**Comment by bozoweed** [comment]
also you can try to map /app/flaresolverr_service.py to a path on host and then take the raw from this PR and past it inside, that can fix your issue easly

**Comment by ObstinateM** [comment]
> > I have also apply the update manualy and worked like sharmed thank you so much contributor <3 keep doing <3
> 
> 
> 
> Unfortunately I can't edit the file.

Just another solution for this,

When you vim into the file, edit 
it and then :wq!
That forces the overwrite, worked like a charm for me

**Comment by TheRealBix** [comment]
I took the liberty to build and publish the docker image, this will help some newbies like me over here.
@tenettow @ilike2burnthing tell me if you want me to remove it.

https://hub.docker.com/r/therealbix/flaresolverr

**Comment by tifo71** [comment]
> I took the liberty to build and publish the docker image, this will help some newbies like me over here. @tenettow @ilike2burnthing tell me if you want me to remove it.
> 
> https://hub.docker.com/r/therealbix/flaresolverr

oh great thanks

**Comment by rak4100** [comment]
> I took the liberty to build and publish the docker image, this will help some newbies like me over here. @tenettow @ilike2burnthing tell me if you want me to remove it.
> 
> https://hub.docker.com/r/therealbix/flaresolverr

Hello , 
I'm not good at computers at all, I'm on unraid & I've been struggling with vim for hours. 
You saved my evening & you saved me from a headache.

Thank you so much !!!

**Comment by tifo71** [comment]
@bozoweed Thanks so much man I managed to modify the file. And everything works perfectly. Thanks again for your clear and precise explanations.

**Comment by tifo71** [comment]
thanks also to @21hsmw for the fix

**Comment by ilike2burnthing** [comment]
[v3.3.20](https://github.com/FlareSolverr/FlareSolverr/releases/v3.3.20)

**Pull request merged**
